default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  host:     <%= ENV["HOST"] %>
  database: <%= ENV["DATABASE"] %>
  username: <%= ENV["USER_NAME"] %>
  password: <%= ENV["PASSWORD"] %>

test:
  <<: *default
  database: web1_test

production:
  primary: &primary_production
    <<: *default
    database: web1_production
    username: web1
    password: <%= ENV["WEB1_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: web1_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: web1_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: web1_production_cable
    migrations_paths: db/cable_migrate
